### ISSUE TITLE
java.lang.NoClassDefFoundError: lombok/ast/AstVisitor

### ISSUE THREAD

**Issue by sjoe** [stephanenicolas/Quality-Tools-for-Android#27]
Hi I have just pulled the project and wanted to build it with:

```
mvn clean install
```

Then I received the following error:

```
[INFO] --- android-maven-plugin:3.6.1:lint (lint) @ android-sample ---
[INFO] Performing lint analysis.
[INFO] Writing Lint XML report in D:\project\mobile\Quality-Tools-for-Android\android-sample\target\lint-results\lint-results.xml
[INFO] Running command: D:\apps\Android\android-sdk-r22_3\tools\lint.bat
[INFO] with parameters: [--showall, --xml, D:\project\mobile\Quality-Tools-for-Android\android-sample\target\lint-results\lint-results.xml, --sources, D:\project\mobile\Quality-Tools-for-Android\andro
id-sample\src\main\java, D:\project\mobile\Quality-Tools-for-Android\android-sample, --exitcode]
[INFO] Exception in thread "main" java.lang.NoClassDefFoundError: lombok/ast/AstVisitor
[INFO]  at com.android.tools.lint.checks.BuiltinIssueRegistry.<clinit>(BuiltinIssueRegistry.java:46)
[INFO]  at com.android.tools.lint.Main.run(Main.java:127)
[INFO]  at com.android.tools.lint.Main.main(Main.java:112)
[INFO] Caused by: java.lang.ClassNotFoundException: lombok.ast.AstVisitor
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[INFO]  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[INFO]  at java.security.AccessController.doPrivileged(Native Method)
[INFO]  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO]  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[INFO]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by sjoe** [comment]
Sorry it is an Android-Tools error:
http://tools.android.com/knownissues
