### ISSUE TITLE
Maven build fails on Mac JDK 1.6

### ISSUE THREAD

**Issue by hborders** [stephanenicolas/Quality-Tools-for-Android#39]
Everything builds fine when I use JDK 1.7 on my Mac. I suspect this is related to one of these JDK bugs:

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7073508
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7073477

Failing output is below.

```
LT-A8-120617:Quality-Tools-for-Android heath.borders$ mvn -version
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 10:22:22-0500)
Maven home: /usr/local/Cellar/maven/3.1.1/libexec
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.8.5", arch: "x86_64", family: "mac"
LT-A8-120617:Quality-Tools-for-Android heath.borders$
LT-A8-120617:Quality-Tools-for-Android heath.borders$ mvn clean install -P jacoco
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] android-sample-parent
[INFO] android-sample
[INFO] android-sample-tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building android-sample-parent 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ android-sample-parent ---
[INFO] Deleting /Users/heath.borders/workspace/Quality-Tools-for-Android/target
[INFO] 
[INFO] --- lint-maven-plugin:0.0.6:check (default) @ android-sample-parent ---
PROFILES: [Profile {id: default, source: pom}, Profile {id: emma, source: pom}, Profile {id: cobertura, source: pom}, Profile {id: uiautomator, source: pom}, Profile {id: espresso, source: pom}, Profile {id: spoon, source: pom}, Profile {id: jacoco, source: pom}, Profile {id: monkey, source: pom}, Profile {id: cycle, source: pom}, Profile {id: monkeyrunner, source: pom}]
[INFO] Writing summary report
[INFO] [LINT] Completed with no violations
[INFO] Writing xml report
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ android-sample-parent ---
[INFO] Installing /Users/heath.borders/workspace/Quality-Tools-for-Android/pom.xml to /Users/heath.borders/.m2/repository/com/octo/android/android-sample-parent/0.0.1-SNAPSHOT/android-sample-parent-0.0.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building android-sample 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ android-sample ---
[INFO] Deleting /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target
[INFO] 
[INFO] --- lint-maven-plugin:0.0.6:check (default) @ android-sample ---
PROFILES: [Profile {id: default, source: pom}, Profile {id: emma, source: pom}, Profile {id: cobertura, source: pom}, Profile {id: uiautomator, source: pom}, Profile {id: spoon, source: pom}, Profile {id: jacoco, source: pom}, Profile {id: monkey, source: pom}, Profile {id: cycle, source: pom}, Profile {id: monkeyrunner, source: pom}]
[INFO] Writing summary report
[INFO] [LINT] Completed with no violations
[INFO] Writing xml report
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:generate-sources (default-generate-sources) @ android-sample ---
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[INFO] /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/build-tools/19.1.0/aapt [package, -f, --no-crunch, -I, /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/platforms/android-17/android.jar, -M, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/AndroidManifest.xml, -S, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/res, -m, -J, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/generated-sources/r, --output-text-symbols, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target, --auto-add-overlay]
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.9.1:check (checkstyle-check) @ android-sample ---
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ android-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/src/main/resources
[INFO] skip non existing resourceDirectory /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/generated-sources/extracted-dependencies/src/main/resources
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:consume-aar (default-consume-aar) @ android-sample ---
[INFO] Extracting classes for all aar dependencies
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ android-sample ---
[INFO] Compiling 5 source files to /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/classes
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:proguard (default-proguard) @ android-sample ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.6.2.201302030002:instrument (instrument-classes) @ android-sample ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ android-sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ android-sample ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ android-sample ---
[INFO] No tests to run.
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:emma (default-emma) @ android-sample ---
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:dex (default-dex) @ android-sample ---
[INFO] /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java [-Xmx1024M, -jar, /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/build-tools/19.1.0/lib/dx.jar, --dex, --output=/Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/classes.dex, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/classes, /Users/heath.borders/.m2/repository/org/jacoco/org.jacoco.agent/0.6.2.201302030002/org.jacoco.agent-0.6.2.201302030002-runtime.jar, /Users/heath.borders/.m2/repository/android/support/compatibility-v4/19/compatibility-v4-19.jar, /Users/heath.borders/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar]
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ android-sample ---
[INFO] Building jar: /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/android-sample-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:apk (default-apk) @ android-sample ---
[INFO] Enabling debug build for apk.
[INFO] /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/build-tools/19.1.0/aapt [package, -f, -M, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/AndroidManifest.xml, -S, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/res, --auto-add-overlay, -I, /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/platforms/android-17/android.jar, -F, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/android-sample-0.0.1-SNAPSHOT.ap_, --debug-mode]
[INFO] 
[INFO] --- jacoco-maven-plugin:0.6.2.201302030002:restore-instrumented-classes (restore-instrumented-classes) @ android-sample ---
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:internal-pre-integration-test (default-internal-pre-integration-test) @ android-sample ---
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:internal-integration-test (default-internal-integration-test) @ android-sample ---
[INFO] 
[INFO] >>> findbugs-maven-plugin:2.5.2:check (findbugs-check) @ android-sample >>>
[INFO] 
[INFO] --- findbugs-maven-plugin:2.5.2:findbugs (findbugs) @ android-sample ---
[INFO] Fork Value is true
     [java] The following classes needed for analysis were missing:
     [java]   java.rmi.Remote
     [java] Missing classes: 1
[INFO] Done FindBugs Analysis....
[INFO] 
[INFO] <<< findbugs-maven-plugin:2.5.2:check (findbugs-check) @ android-sample <<<
[INFO] 
[INFO] --- findbugs-maven-plugin:2.5.2:check (findbugs-check) @ android-sample ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] 
[INFO] >>> maven-pmd-plugin:2.7.1:check (pmd-check) @ android-sample >>>
[INFO] 
[INFO] --- maven-pmd-plugin:2.7.1:pmd (pmd) @ android-sample ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] <<< maven-pmd-plugin:2.7.1:check (pmd-check) @ android-sample <<<
[INFO] 
[INFO] --- maven-pmd-plugin:2.7.1:check (pmd-check) @ android-sample ---
[INFO] 
[INFO] 
[INFO] >>> maven-pmd-plugin:2.7.1:cpd-check (pmd-check) @ android-sample >>>
[INFO] 
[INFO] --- maven-pmd-plugin:2.7.1:cpd (cpd) @ android-sample ---
[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO] 
[INFO] <<< maven-pmd-plugin:2.7.1:cpd-check (pmd-check) @ android-sample <<<
[INFO] 
[INFO] --- maven-pmd-plugin:2.7.1:cpd-check (pmd-check) @ android-sample ---
[INFO] 
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ android-sample ---
[INFO] Installing /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/android-sample-0.0.1-SNAPSHOT.apk to /Users/heath.borders/.m2/repository/com/octo/android/android-sample/0.0.1-SNAPSHOT/android-sample-0.0.1-SNAPSHOT.apk
[INFO] Installing /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/pom.xml to /Users/heath.borders/.m2/repository/com/octo/android/android-sample/0.0.1-SNAPSHOT/android-sample-0.0.1-SNAPSHOT.pom
[INFO] Installing /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/android-sample-0.0.1-SNAPSHOT.jar to /Users/heath.borders/.m2/repository/com/octo/android/android-sample/0.0.1-SNAPSHOT/android-sample-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:lint (lint) @ android-sample ---
[INFO] Performing lint analysis.
[INFO] Writing Lint XML report in /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/lint-results/lint-results.xml
[INFO] Running command: /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/tools/lint
[INFO] with parameters: [--showall, --xml, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/target/lint-results/lint-results.xml, --sources, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample/src/main/java, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample, --exitcode]
[INFO] Lint analysis completed successfully.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building android-sample-tests 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ android-sample-tests ---
[INFO] Deleting /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target
[INFO] 
[INFO] --- lint-maven-plugin:0.0.6:check (default) @ android-sample-tests ---
PROFILES: [Profile {id: emma, source: pom}, Profile {id: spoon, source: pom}, Profile {id: jacoco, source: pom}]
[INFO] Writing summary report
[INFO] [LINT] Completed with no violations
[INFO] Writing xml report
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:generate-sources (default-generate-sources) @ android-sample-tests ---
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[INFO] /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/build-tools/19.1.0/aapt [package, -f, --no-crunch, -I, /Users/heath.borders/android/adt-bundle-mac-x86_64/sdk/platforms/android-17/android.jar, -M, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/AndroidManifest.xml, -S, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/res, -A, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target/generated-sources/combined-assets/assets, -m, -J, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target/generated-sources/r, --output-text-symbols, /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target, --auto-add-overlay]
[INFO] 
[INFO] --- build-helper-maven-plugin:1.8:add-source (add-source) @ android-sample-tests ---
[INFO] Source directory: /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target/generated-sources/annotations added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ android-sample-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/src/main/resources
[INFO] skip non existing resourceDirectory /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target/generated-sources/extracted-dependencies/src/main/resources
[INFO] 
[INFO] --- android-maven-plugin:3.8.2:consume-aar (default-consume-aar) @ android-sample-tests ---
[INFO] Extracting classes for all aar dependencies
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ android-sample-tests ---
[INFO] Compiling 8 source files to /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/target/classes
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundBoxProcessor process
INFO: mirror org.boundbox.BoundBox
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: class ->HelloAndroidActivity
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: nested ->false
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner addTypeToImport
INFO: Adding to imports com.octo.android.sample.ui.HelloAndroidActivity
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: super class -> com.octo.android.sample.ui.HelloAndroidActivity-->android.support.v4.app.FragmentActivity
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: class ->ButtonClickListener
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: nested ->true
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner addTypeToImport
INFO: Adding to imports com.octo.android.sample.ui.HelloAndroidActivity.ButtonClickListener
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitTypeAsClass
INFO: super class -> com.octo.android.sample.ui.HelloAndroidActivity.ButtonClickListener-->java.lang.Object
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitExecutable
INFO: executable -><init>
Jun 10, 2014 3:07:54 PM org.boundbox.processor.BoundClassScanner visitExecutable
INFO: executable ->onClick
java.lang.NullPointerException
    at org.boundbox.model.FieldInfo.<init>(FieldInfo.java:34)
    at org.boundbox.model.MethodInfo.<init>(MethodInfo.java:61)
    at org.boundbox.processor.BoundClassScanner.visitExecutable(BoundClassScanner.java:156)
    at org.boundbox.processor.BoundClassScanner.visitExecutable(BoundClassScanner.java:31)
    at com.sun.tools.javac.code.Symbol$MethodSymbol.accept(Symbol.java:1230)
    at org.boundbox.processor.BoundClassScanner.visitTypeAsClass(BoundClassScanner.java:145)
    at org.boundbox.processor.BoundClassScanner.visitTypeAsClass(BoundClassScanner.java:31)
    at javax.lang.model.util.ElementKindVisitor6.visitType(ElementKindVisitor6.java:118)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:835)
    at org.boundbox.processor.BoundClassScanner.visitTypeAsClass(BoundClassScanner.java:145)
    at org.boundbox.processor.BoundClassScanner.visitTypeAsClass(BoundClassScanner.java:31)
    at javax.lang.model.util.ElementKindVisitor6.visitType(ElementKindVisitor6.java:118)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:835)
    at org.boundbox.processor.BoundClassScanner.scan(BoundClassScanner.java:49)
    at org.boundbox.processor.BoundBoxProcessor.process(BoundBoxProcessor.java:182)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:627)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:556)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:701)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:987)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at com.sun.tools.javac.main.Main.compile(Main.java:279)
    at com.sun.tools.javac.main.Main.compile(Main.java:270)
    at com.sun.tools.javac.Main.compile(Main.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:551)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:526)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:167)
    at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:678)
    at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/src/main/java/com/octo/android/sample/test/HelloAndroidActivityBoundBoxTest.java:[9,33] cannot find symbol
symbol  : class BoundBoxOfHelloAndroidActivity
location: package com.octo.android.sample.ui
[ERROR] /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/src/main/java/com/octo/android/sample/test/HelloAndroidActivityBoundBoxTest.java:[15,12] cannot find symbol
symbol  : class BoundBoxOfHelloAndroidActivity
location: class com.octo.android.sample.test.HelloAndroidActivityBoundBoxTest
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] android-sample-parent ............................. SUCCESS [1.235s]
[INFO] android-sample .................................... SUCCESS [22.231s]
[INFO] android-sample-tests .............................. FAILURE [0.773s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.225s
[INFO] Finished at: Tue Jun 10 15:07:54 CDT 2014
[INFO] Final Memory: 34M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project android-sample-tests: Compilation failure: Compilation failure:
[ERROR] /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/src/main/java/com/octo/android/sample/test/HelloAndroidActivityBoundBoxTest.java:[9,33] cannot find symbol
[ERROR] symbol  : class BoundBoxOfHelloAndroidActivity
[ERROR] location: package com.octo.android.sample.ui
[ERROR] /Users/heath.borders/workspace/Quality-Tools-for-Android/android-sample-tests/src/main/java/com/octo/android/sample/test/HelloAndroidActivityBoundBoxTest.java:[15,12] cannot find symbol
[ERROR] symbol  : class BoundBoxOfHelloAndroidActivity
[ERROR] location: class com.octo.android.sample.test.HelloAndroidActivityBoundBoxTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :android-sample-tests
```

**Comment by hborders** [comment]
This seems related to https://github.com/stephanenicolas/boundbox/issues/26
