### ISSUE TITLE
Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo:thirdparty

### ISSUE THREAD

**Issue by krschultz** [stephanenicolas/Quality-Tools-for-Android#4]
Maven 3.0.4
android-maven-plugin 3.5.2-SNAPSHOT
mvn clean install -X

```
[ERROR] Failed to execute goal on project android-sample-ui-tests: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]: Failed to read artifact descriptor for com.google.android:uiautomator:jar:4.2.2: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project android-sample-ui-tests: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:158)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
    ... 22 more
Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:150)
    ... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.google.android:uiautomator:jar:4.2.2
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
    at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
    ... 25 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized.
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
    at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
    at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
    ... 28 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized.
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
    at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized, ReasonPhrase:Unauthorized.
    at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:839)
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
    ... 4 more
[ERROR] 
```

**Comment by stephanenicolas** [comment]
UI Automator is not available publicly yet.

The Quality Tools for Android is using an early stage of the modified
android maven plugin and still needs a copy of ui automator to be deployed
and accessible to your maven copy. Internally at OCTO, we deployed on our
nexus but we can't distribute it outside for copyright reasons.

Manfred, author of the android maven plugin, is currently working on this.
In the meanwhile, you can either :
- deploy uiautomator jar on your own nexus
- use the SDK deployer to get uiautomator installed in your personnal maven
  repo
- install ui automator by hand using maven import-file goals

S.

2013/3/22 Kevin Schultz notifications@github.com

> Maven 3.0.4
> android-maven-plugin 3.5.2-SNAPSHOT
> mvn clean install -X
> 
> [ERROR] Failed to execute goal on project android-sample-ui-tests: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]: Failed to read artifact descriptor for com.google.android:uiautomator:jar:4.2.2: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project android-sample-ui-tests: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
>     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
>     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
>     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
>     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
>     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
>     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
>     at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:601)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
> Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.octo.android:android-sample-ui-tests:jar:0.0.1-SNAPSHOT: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
>     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:158)
>     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
>     ... 22 more
> Caused by: org.sonatype.aether.collection.DependencyCollectionException: Failed to collect dependencies for [com.google.android:android:jar:4.1.1.4 (provided), com.google.android:uiautomator:jar:4.2.2 (provided), junit:junit:jar:3.8.2 (provided)]
>     at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:258)
>     at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:308)
>     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:150)
>     ... 23 more
> Caused by: org.sonatype.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.google.android:uiautomator:jar:4.2.2
>     at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:296)
>     at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:186)
>     at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCollector.java:412)
>     at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:240)
>     ... 25 more
> Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized.
>     at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
>     at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
>     at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
>     at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:281)
>     ... 28 more
> Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact com.google.android:uiautomator:pom:4.2.2 from/to octo.thirdparty (https://projets.octo.com/nexus/content/repositories/thirdparty/): Not authorized, ReasonPhrase:Unauthorized.
>     at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
>     at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
>     at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
>     at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>     at java.lang.Thread.run(Thread.java:722)
> Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Not authorized, ReasonPhrase:Unauthorized.
>     at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:839)
>     at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
>     at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
>     at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
>     at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
>     ... 4 more
> [ERROR]
> 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/Quality-Tools-for-Android/issues/4
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................
